# -*- coding: utf-8 -*-
"""tas_kagit_makas_oyunu_ELIF_HANEDAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbtl3oiBTgd32AhTAmnYyUOVxu60Odul
"""

# pip install pygame

import random
import time

def tas_kagit_makas_ELIF_HANEDAN():
    # Oyun seçenekleri ve ASCII sembolleri
    secenekler = ['Taş', 'Kağıt', 'Makas']
    semboller = {
        'Taş': '''taş:
    _______
---'   ____)
      (_____)
      (____)
      (____)
---.__(___)
''',
        'Kağıt': '''kağıt:
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
''',
        'Makas': '''makas:
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
    }

    # Zorluk seviyeleri
    zorluk_seviyeleri = {
        'Kolay': 10,  # süre sınırı 10 saniye
        'Orta': 5,    # süre sınırı 5 saniye
        'Zor': 3      # süre sınırı 3 saniye
    }

    print("🎮 Hoş geldiniz! Taş, Kağıt, Makas oyununa başlayalım! 🎮")
    print("Kurallar:")
    print("1️⃣ Bu oyunda, sen ve bilgisayar sırasıyla Taş, Kağıt veya Makas seçimi yapacaksınız.")
    print("2️⃣ Taş, Makas'ı yener. Makas, Kağıt'ı yener. Kağıt, Taş'ı yener.")
    print("3️⃣ İlk iki turu kazanan, oyunun galibi olur. Eğer bir tur berabere biterse, o tur tekrarlanır.")
    print("4️⃣ Her tur için belirli bir süre sınırı vardır.")
    print("5️⃣ Oyuncu zorluk seviyesini seçebilir: Kolay, Orta, Zor.")
    print("6️⃣ Oyun sonunda tekrar oynamak isteyip istemediğin sorulacak. Eğer devam etmek istemezsen 'Hayır' yazman yeterli.")
    print("İyi şanslar! 🥳\n")

    # Zorluk seviyesini seçme
    zorluk = input("Zorluk seviyesini seçin (Kolay/Orta/Zor): ").capitalize()
    while zorluk not in zorluk_seviyeleri:
        print(f"Geçersiz seçim: '{zorluk}'! Lütfen 'Kolay', 'Orta' veya 'Zor' seçin.")
        zorluk = input("Tekrar deneyin: ").capitalize()

    sure_siniri = zorluk_seviyeleri[zorluk]

    # Sayaçlar
    oyuncu_galibiyetleri = 0
    bilgisayar_galibiyetleri = 0
    oyun_sayisi = 0

    # Oyunun ana döngüsü
    while True:
        oyun_sayisi += 1
        oyuncu_tur_sayaci = 0
        bilgisayar_tur_sayaci = 0

        # Tur döngüsü
        while oyuncu_tur_sayaci < 2 and bilgisayar_tur_sayaci < 2:
            print(f"\nOyun {oyun_sayisi}, Tur: {oyuncu_tur_sayaci + bilgisayar_tur_sayaci + 1}")
            print(f"Senin Skorun: {oyuncu_tur_sayaci}, Bilgisayarın Skoru: {bilgisayar_tur_sayaci}")

            # Oyuncunun seçimi için zaman sınırlaması
            baslangic_zamani = time.time()
            oyuncu_secimi = input(f"Lütfen seçiminizi yapın (Taş, Kağıt, Makas). {sure_siniri} saniye içinde seçim yapın: ").capitalize()
            gecen_sure = time.time() - baslangic_zamani

            if gecen_sure > sure_siniri:
                print("Süre doldu, geçersiz seçim!")
                oyuncu_secimi = None
            else:
                while oyuncu_secimi not in secenekler:
                    print(f"Geçersiz seçim: '{oyuncu_secimi}'! Lütfen 'Taş', 'Kağıt' veya 'Makas' kelimelerinden birini seçin.")
                    oyuncu_secimi = input("Tekrar deneyin: ").capitalize()

            # Bilgisayar seçimi
            bilgisayar_secimi = random.choice(secenekler)

            # Seçimlerin gösterilmesi
            if oyuncu_secimi:
                print(f"\nSenin seçimin:\n{semboller[oyuncu_secimi]}")
            print(f"Bilgisayarın seçimi:\n{semboller[bilgisayar_secimi]}")

            # Tur kazananını belirleme
            if oyuncu_secimi == bilgisayar_secimi:
                print("Berabere!")
            elif (oyuncu_secimi == 'Taş' and bilgisayar_secimi == 'Makas') or \
                 (oyuncu_secimi == 'Kağıt' and bilgisayar_secimi == 'Taş') or \
                 (oyuncu_secimi == 'Makas' and bilgisayar_secimi == 'Kağıt'):
                print("Bu turu sen kazandın!")
                oyuncu_tur_sayaci += 1
            else:
                print("Bu turu bilgisayar kazandı!")
                bilgisayar_tur_sayaci += 1

            # Son şans mesajı
            if oyuncu_tur_sayaci == 1 and bilgisayar_tur_sayaci == 1:
                print("Bu son şansın, hadi kazanabilirsin!")

        # Oyun galibini belirleme
        if oyuncu_tur_sayaci == 2:
            print("KAZANDIN")
            print("Tebrikler! Bu oyunu kazandın! 🎉")
            oyuncu_galibiyetleri += 1
        else:
            print("KAYBETTİN")
            print("Üzgünüm, bu oyunu bilgisayar kazandı. 😔")
            bilgisayar_galibiyetleri += 1

        # Tekrar oynama isteği
        tekrar_oyna = input("Tekrar oynamak ister misin? (Evet/Hayır): ").capitalize()
        if tekrar_oyna == 'Hayır':
            print(f"\nOyun Bitti! Toplam oyunlar: {oyun_sayisi}, Senin galibiyetlerin: {oyuncu_galibiyetleri}, Bilgisayar galibiyetleri: {bilgisayar_galibiyetleri}")
            break

        # Bilgisayarın devam edip etmeyeceğine karar verme
        bilgisayar_devam = random.choice(['Evet', 'Hayır'])
        if bilgisayar_devam == 'Hayır':
            print(f"\nBilgisayar artık oynamak istemiyor. Toplam oyunlar: {oyun_sayisi}, Senin galibiyetlerin: {oyuncu_galibiyetleri}, Bilgisayar galibiyetleri: {bilgisayar_galibiyetleri}")
            break

# Fonksiyonu çağırarak oyunu başlatabilirsiniz
tas_kagit_makas_ELIF_HANEDAN()